name: release.yml
on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish-to-registry:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Publish to registry
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm publish --access public